export const api = {
  getAllCategories: '/categories',
  createCategories: '/categories',
  deleteCategory: (id) => `/categories/${id}`,
  updateCategory: (id) => `/categories/${id}`,
  getCategoryId: (id) => `/categories/${id}`,
  upLoadImages: '/upload',
  deleteImages: '/upload/destroy',
  getAllProducts: '/products',
  createProducts: '/products',
  deleteProduct: (id) => `/products/${id}`,
  updateProduct: (id) => `/products/${id}`,
  getProductId: (id) => `/products/${id}`,
  getProductByCategory: `/custom/getProdcutById`,
  login: '/auth/login',
  register: '/auth/register',
  getContact: '/contacts',
  deleteContacts: (id) => `/contacts/${id}`,
}